version: '3.8'

services:
  db:
    image: postgres:15
    container_name: blogger-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blogger-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
